api/urls.py
from django.urls import path, include
from rest_framework import routers
from .import views


router = routers.DefaultRouter()
router.register('questions', views.QuestionsViewSet)
router.register('choices', views.ChoiceViewSet)
router.register('articles', views.ArticleViewSet)
router.register('authors', views.AuthorViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls-app/', include('polls.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/vote', views.vote, name='vote'),
]

polls/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', db_index=True)

    @admin.display(boolean=True, ordering='pub_date', description='Published recently')
    def was_published_recently(self):

        now = timezone.now()
        return now - timezone.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.question.question_text} : {self.choice_text}'

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone

# Create your views here.
from .models import Question, Choice
def index(request):
    questions = Question.objects.filter(pub_date__lte = timezone.now()).order_by('pub_date')[:5]
    context = {'questions': questions}
    return render(request, 'polls/index.html', context)


def detail(request, question_id: int):
    question = get_object_or_404(Question, id=question_id)
    context = {'question': question}
    return render(request, 'polls/detail.html', context)
def vote(request, question_id: int):
    question = get_object_or_404(Question, id=question_id)
    choice_id = int(request.POST['choice_id'])
    choice = question.choices.get(id=choice_id)
    choice.votes += 1
    choice.save()
    return redirect('polls:detail', question_id)

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block tittle %}Polls APP{% endblock %}</title>
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block title %}Poll{% endblock %}

{% block body %}
    <h1>{{ question.question_text}}</h1>
    <form action="{% url 'polls:vote' question.id %}" method="POST">
        {% csrf_token %}
        {% for choice in question.choices.all %}
        <input type="radio" name="choice_id" value="{{ choice.id }}"/>
        {{ choice.choice_text }} -- {{ choice.votes }}<br>
        {% endfor %}

        <input type="submit" value="vote"/>
    </form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block body %}
    {% if questions %}
        <ul>
            {% for question in questions %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}