api/urls.py
from django.urls import path, include
from rest_framework import routers
from .import views


router = routers.DefaultRouter()
router.register('questions', views.QuestionsViewSet)
router.register('choices', views.ChoiceViewSet)
router.register('articles', views.ArticleViewSet)
router.register('authors', views.AuthorViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/like', views.like, name='like'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls-app/', include('polls.urls')),
]

articles/models.py
from django.db import models
from django.contrib import admin
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200)
    text = models.CharField(max_length=3000)
    author = models.CharField(max_length=200)
    like_count = models.IntegerField(default=0)

    @admin.display(
        boolean=True,
        description="Is popular?",
        ordering='like_count'
    )

    def is_popular(self):
        return self.like_count >= 100

    def __str__(self):
        return self.title

articles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Article
# Create your views here.


def index(request):
    articles = Article.objects.all()
    context = {'all_articles': articles}
    return render(request, 'articles/index.html', context)

def detail(request, article_id: int):
    article = get_object_or_404(Article, id=article_id)
    context = {'article': article}
    return render(request, 'articles/detail.html', context)

def like(request, article_id: int):
    assert request.method == 'POST'
    article_id = request.POST['article_id']
    article = get_object_or_404(Article, id=article_id)
    article.like_count += 1
    article.save()
    return redirect('articles:detail', article_id)

articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block tittle %}Articles {% endblock %}</title>
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

articles/templates/articles/detail.html
{% extends 'articles/base.html' %}

{% block body %}
    <h1>{{ article.title }}</h1>
    <i>{{ article.author }}</i>
    <p><strong>Likes: {{ article.like_count }}</strong></p>
    <form method="post" action="{% url 'articles:like' article.id %}">
        {% csrf_token %}
        <input type="hidden" name="article_id" value="{{ article.id }}"/>
        <input type="submit" value="Like"/>
    </form>
{% endblock %}

articles/templates/articles/index.html
{% extends 'articles/base.html' %}

{% block body %}
    {% if all_articles %}
        <h1>All articles</h1>
        <ul>
            {% for article in all_articles %}
                <li><a href="{% url 'articles:detail' article.id %}">{{ article.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No articles are available</p>
    {% endif %}
{% endblock %}