api/urls.py
from django.urls import path, include
from rest_framework import routers
from .import views


router = routers.DefaultRouter()
router.register('questions', views.QuestionsViewSet)
router.register('choices', views.ChoiceViewSet)
router.register('articles', views.ArticleViewSet)
router.register('authors', views.AuthorViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls-app/', include('polls.urls')),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>', views.category_detail, name='category_detail'),
    path('product/<int:product_id>', views.product_detail, name='product_detail'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart')
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.




class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    price = models.FloatField(default=0.0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')

    def __str__(self):
        return self.name

class OrderEntry(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='+')
    count = models.IntegerField(default=0)
    order = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='order_entries')

    def __str__(self):
        return f'{self.order.id} {self.product} {self.count}'

    @property
    def price(self):
        return self.product.price * self.count

class Order(models.Model):
    profile = models.ForeignKey('Profile', on_delete=models.CASCADE, related_name='orders')
    status = models.CharField(max_length=20, default="INITIAL")\

    def __str__(self):
        return f'{self.id} {self.profile} {self.status}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    shopping_cart = models.OneToOneField(Order, on_delete=models.SET_NULL,
                                          null=True, blank=True, related_name='+')

    def __str__(self):
        return self.user

shop/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpRequest
from .models import Category, Product, Profile, Order, OrderEntry

# Create your views here.


def index(request):
    return render(request, 'shop/index.html', {'categories': Category.objects.all()})

def category_detail(request, category_id: int):
    return render(request, 'shop/category_detail.html',{
        'category': get_object_or_404(Category, id=category_id),
    })

def product_detail(request, product_id: int):
    return render(request, 'shop/product_detail.html',{
        'product': get_object_or_404(Product, id=product_id),
    })
@login_required
def add_to_cart(request: HttpRequest):
    profile = request.user.profile
    if not request.user.profile.shopping_cart:
        request.user.profile.shopping_cart = Order(profile=request.user.profile)
        request.user.profile.shopping_cart.save()

    assert request.method== 'POST'
    product_id = request.POST['product_id']
    product = get_object_or_404(Product, id=request.POST['product_id'])
    order_entry = OrderEntry.shoping_card.order_entries.get(product=product).first()
    if not order_entry:
        order_entry = profile.shopping_cart.order_entries.create(product=product, count=0)
        order_entry.count += 1
        order_entry.save()
    OrderEntry.objects.create(product=product, count=1,
                                            order=profile.shopping_cart)

    return redirect('shop:product_detail', product_id)

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
        {% if user.is_authenticated %}
        <form action="{% url 'logout' %}?next={{ request.path }}" method="post">
            {% csrf_token %}
            <input type="submit" value="Logout" class="btn-danger"/>
        </form>
    {% else %}
        <a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-info">Login</a>
    {% endif %}
<a href="{% url 'shop:index' %}">Go to Home</a>
{% block body %}{% endblock %}
</body>
</html>

shop/templates/shop/category_detail.html
{% extends 'shop/base.html' %}

{% block body %}
    <h1>{{ category.name }}</h1>
    <ul>
         {% for product in category.products.all %}
            <li><a href="{% url 'shop:product_detail' product.id %}">{{ product.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

shop/templates/shop/index.html
{% extends 'shop/base.html' %}

{% block body %}
    {% if not categories %}
        <h1>There are no categories</h1>
    {% else %}
        <h1>Categories</h1>
        <ul>
            {% for category in categories %}
                <li>
                    <a href="{% url 'shop:category_detail' category.id %}">{{ category.name }}</a>
                    <ul>
                        {% for product in category.products.all %}
                            <li><a href="{% url 'shop:product_detail' product.id %}">{{ product.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}

{% block body %}
    <h1>{{ product.name }}</h1>
    <p>{{ product.description }} </p><p>{{ product.price }} $</p>
    <p>Category:
        <a href="{% url 'shop:category_detail' product.category.id %}">
            {{ product.category.name }}
        </a>
    </p>
    {% if user.is_autentificated %}
        <form action="{% url 'shop:add_to_cart' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="product_id" value="{{ product.id }}">
            <input type="submit" value="add_to_card">
        </form>
    {% else %}
        2
{% endblock %}